### ISSUE TITLE
Double-quotes aren't parsed in DOSBox Staging on Windows

### ISSUE THREAD

**Issue by kcgen** [tyrells/dosbox-svn-shaders#7]
![xbr-parse-problem](https://user-images.githubusercontent.com/1557255/112246310-ae346700-8c0f-11eb-9b8c-2e732ea207dd.PNG)

Replacing the `"space separated items"`, such as:

``` c++
#pragma parameter XBR_EQ_THRESHOLD "Eq Threshold" 0.6 0.0 2.0 0.1
#pragma parameter XBR_LV2_COEFFICIENT "Lv2 Coefficient" 2.0 1.0 3.0 0.1
```

with the following, fixes the issue:

``` c++
#pragma parameter XBR_EQ_THRESHOLD Eq_Threshold 0.6 0.0 2.0 0.1
#pragma parameter XBR_LV2_COEFFICIENT Lv2_Coefficient 2.0 1.0 3.0 0.1
```

**Comment by tyrells** [comment]
Hi @kcgen. The #pragma lines aren't actually being used in the shader code, and have just been kept around so that users know the recommended/min/max values that they can use to adjust these parameters. The actual values used in the code are the #define statements later in the code. 

This being the case, I have commented out the #pragma code completely. Let me know if this fixes your issue.

**Comment by kcgen** [comment]
![Capture2](https://user-images.githubusercontent.com/1557255/112248420-205a7b00-8c13-11eb-9726-62146b8b21a8.PNG)

Tested a handful and all are working nicely :-)

Thank you @tyrells!
